distancePair class and RecommenderServlet
googleinterns/step241-2020 pull request #38
Opened 2020-09-18 14:19 UTC by raniarusly

2020-09-18 15:14 UTC, MostafaGabriel reviewed
Thanks Rania!

2020-09-18 15:14 UTC, MostafaGabriel commented on src/main/java/com/google/sps/servlets/RecommenderServlet.java
> +    for(String factor : FACTORS) {
```suggestion
    for (String factor : FACTORS) {
```

2020-09-18 15:14 UTC, MostafaGabriel commented on src/main/java/com/google/sps/servlets/RecommenderServlet.java
> +    for(String factor : FACTORS) {
```suggestion
    for (String factor : FACTORS) {
```

2020-09-18 15:14 UTC, MostafaGabriel commented on src/main/java/com/google/sps/servlets/RecommenderServlet.java
> +  private final String[] FACTORS = {"price", "crowd"};
These are stored as `price-rating` and `crowd-rating` [ref](https://github.com/googleinterns/step241-2020/blob/master/src/main/java/com/google/sps/servlets/RecommendationServlet.java#L96-L97) Please make sure to match the property name in Datastore and the HTTP request as well for the user input as you're using the same name

2020-09-22 07:31 UTC, lornaarmstrong requested changes

2020-09-22 07:31 UTC, lornaarmstrong commented on src/main/java/com/google/sps/servlets/RecommenderServlet.java
> +  private final String[] FACTORS = {"price-rating", "crowd-rating"};
The name "price-rating" is not correct - take a look at the datastore to check. This effects lots of the other areas of code, as when you search the datastore for this field, it finds nothing.

2020-09-22 11:36 UTC, lornaarmstrong approved these changes
LGTM!

2020-09-22 12:25 UTC, MostafaGabriel approved these changes
LGTM! Thanks Rania :)

2020-09-22 12:25 UTC, MostafaGabriel commented on src/main/java/com/google/sps/servlets/RecommenderServlet.java
> +    for(String factor : FACTORS) {
Please fix :)

2020-09-22 12:43 UTC, merged