Create user directory page layout
googleinterns/step241-2020 pull request #6
Opened 2020-08-18 16:46 UTC by raniarusly

rendered UI
![image](https://user-images.githubusercontent.com/41379082/90541598-cd02e480-e17a-11ea-9a26-d2587c9454c2.png)

2020-08-19 07:18 UTC, lornaarmstrong requested changes
A few minor changes needed but looking good!

2020-08-19 07:18 UTC, lornaarmstrong commented on src/main/webapp/styles/userdir.css
> +  padding:20px;
nit: add a space here

2020-08-19 07:18 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +    <title>Student Recommendations</title>
nit: maybe add a more meaningful title (as this is the general site, not page specific)

2020-08-19 07:18 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +
nit: is this whitespace necessary? you haven't used it anywhere else in the document so maybe looks a little odd.

2020-08-19 07:18 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +          <li><a class="active" href="/">Recommendation Map</a></li>
This wouldn't be the active class, right? this is the user directory page so the /userdir.html should be active instead.

2020-08-19 07:19 UTC, lornaarmstrong commented
Note: Please remove my picture and information from the site. We can use fictional examples of users.

2020-08-20 13:17 UTC, lornaarmstrong requested changes
LGTM! A few minor changes needed but overall, looking great!

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +        <!-- <div class="user-card">
As we aren't using this section, I think we can remove it rather than just have it commented out.

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/styles/landing.css
> +  position:relative;
nit: space needed here

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/styles/landing.css
> +.login-button:hover{
nit: space needed here

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/form.html
> +      <p>Hello! my name is</p>
nit: the punctuation isn't quite right here

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/form.html
> +        <h1>StudentRecs</h1>
nit: are we using "Student Recs", rather than "StudentRecs"?

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/form.html
> +    <title>StudRecs - Form</title>
I think maybe this title could be improved? "StudRecs" isn't a shortening we're using - it might be best to use the full wording.

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/login.html
> +    <title>StudRecs - Welcome!</title>
as above (re: using full title)

2020-08-20 13:17 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +    <title>StudRecs - User Directory</title>
as above (re: using full title)

2020-08-21 12:09 UTC, lornaarmstrong reviewed
Looking great! The changes were a little hard to review so apologies if I missed anything! There are still some things that need changing, like the "StudRecs" title. I'm not sure whether you have or haven't implemented these changes but I think maybe they haven't been pushed yet.

2020-08-21 12:09 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +    <script src="/scripts/userdir.js"></script>
add a hyphen in between separate words to keep consistent

2020-08-21 12:09 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +=======
There are some conflicts that need to be resolved.

2020-08-21 19:20 UTC, raniarusly commented on src/main/webapp/userdir.html
> +    <script src="/scripts/userdir.js"></script>
is it to change the file name to "user-dir.js" ?

2020-08-24 10:22 UTC, lornaarmstrong commented on src/main/webapp/userdir.html
> +    <script src="/scripts/userdir.js"></script>
yes, thanks!

2020-08-24 11:59 UTC, lornaarmstrong approved these changes
LGTM!

2020-08-25 12:12 UTC, MostafaGabriel reviewed
Thanks Rania! Just few nits but looks good overall :)

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/form.html
> +        <h1>Student Recs</h1>
Shall we use `Recommendations` here instead of `Recs` for consistency with the title above?

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/login.html
> +        <h1>Student Recs</h1>
ditto

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/scripts/user-dir.js
> +// Copyright 2019 Google LLC
```suggestion
// Copyright 2020 Google LLC
```

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/scripts/user-dir.js
> +// Copyright 2019 Google LLC
I think it's much clearer to use `directory` instead of `dir` in the file name, same for the html/css files

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/user-dir.html
> +      <h1>Student Recs</h1>
ditto

2020-08-25 12:12 UTC, MostafaGabriel commented on src/main/webapp/user-dir.html
> +      <h2>made by Rania Rusly and Lorna Armstrong</h2>
```suggestion
      <h2>Made by Rania Rusly and Lorna Armstrong</h2>
```

2020-08-25 13:36 UTC, MostafaGabriel approved these changes
Thanks Rania. LGTM!
Please make sure to delete the `images/profilepic{i}.png` files from this pull request before merging as they're unused :)

2020-08-25 13:49 UTC, merged